'use strict'

export default {
	'titleDesign': 'Graphic Design',
	'titleDevelop': 'Web Develop',
	'titleGaming': 'Video Games',
	'homeMenu': 'Home',
	'designMenu': 'Graphic Design',
	'developMenu': 'Web Develop',
	'gamingMenu': 'Video Games',
	'adviceText': 'Touch me and learn a little bit about me',
	'designCardTitle': 'Graphic Design',
	'developCardTitle': 'Web Develop',
	'gamingCardTitle': 'Video Games',
	'abilities': 'Abilities',
	'genre': "Genre's",
	'cardHabIllustration': 'Web Illustration',
	'cardHabUX': 'UX/UI Design',
	'cardHabJS': 'JavaScript Applications',
	'cardHabNode': 'NodeJS Servers',
	'cardHabWebDes': 'Web Design',
	'cardHabAni': 'Web Animations',
	'cardHabResp': 'Responsive Design',
	'cardHabApi': "API's Creation",
	'cardCreative': 'Creative',
	'cardEffective': 'Effective',
	'cardAgil': 'Agil',
	'cardExpressive': 'Expressive',
	'cardClean': 'Clean code',
	'cardReadable': 'Readable',
	'cardQuick': 'Quick',
	'cardFunctional': 'Functional',
	'cardAmazing': 'Amazing',
	'cardMagic': 'Magical',
	'cardFunny': 'Funny',
	'cardGenreAct': 'Action',
	'cardGenreAdv': 'Adventure',
	'cardGenreSpo': 'Sports',
	'cardGenreHor': 'Survival Horror',
	'cardPrinciples': 'Principles',
	'cardLeader': 'Leadership',
	'cardRespect': 'Respect',
	'cardRespon': 'Responsability',
	'cardPerse': 'Perseverance',
	'cardSelf': 'Self-taught',
	'cardSelfC': 'Self-critical',
	'cardReal': 'Realistic',
	'cardAbout': 'A little bit about me',
	'cardAboutTextF': "My name is Steven Anaya, I’m 21 years old and I studied engineering software but but by own decisions I retired to begin a process of constant and evolutionary learning. Until today my carreer as self-taught has given incredible results that I would hardly have achieved before.",
	'cardAboutTextS': "Definitely, leave my career as engineer was the harder decision that I’ve taken until today but I can say but I have pride and more than anything the ability to say that I have	become a web designer and developer thanks to the constancy that I have put in my learning process.",
	'cardTools': 'My learning tools',
	'cardToolsText': "It would be superb to say with certainty that all my knowledge is totally structured by me. I owe a big thank you to all those virtual platforms and to those traditional media that provide clear and useful knowledge. Platzi.co is a platform where I have put my efforts to train as a professional in digital fields and to date, after 4 years, I continue to be surprised with academic content of incredible quality that allow me to be aware of the demands in the industry.",
	'cardGamingInt': 'More than graphics',
	'cardGamingIntTextF': 'Video games are part of the life of some people as a need to be able to imagine, feel, live and remember experiences that are hard to come by in daily life. I grew up surrounded by great experiences that were improving over the years and it would be ungrateful not to give back a bit of how much they have contributed to me, even if it is this way.',
	'cardGamingIntTextS': "A significant part of my memories I owe to videogames because they evoked in me an unimaginable amount of feelings, which as expected, most are pleasant and positive. Also, to leave nothing behind, I feel in duty to mention great titles like Super Mario World, Donkey Kong, Twisted Metal, Battlefield, Call Of Duty, Crash Saga, Halo, Dante's Inferno, Grand Theft Auto, Mortal Kombat, Resident Evil, Tomb Raider and some who, as a matter of memory, more than anything else, do not appear here.",
	'cardGamingLast': 'A dream aim',
	'cardGamingLastText': 'In the beginning I knew that video games required a lot of skills, not only technical but also artistic, that fueled a deep interest in the creation of	video game. Today I have put on my list of "Amazing things to do", become a video game developer where I feel that I can exploit everything that has brought my self-taught process.',
	'cardDevClean': 'Clean and readable code first',
	'cardDevCleanText': 'Good practices and sustainable code are two principles fundamental in my daily life as a developer. When we work under these premises our work environment is benefited enhancing our talent human and technical.',
	'cardDevConc': 'High concurrency and other things',
	'cardDevConcText': 'Nowadays it is fundamental to create highly scalable applications because technological products are increasingly growing abysmally over time. NodeJS and a JavaScript stack allow me to create applications with great support to large numbers of requests, with a structure based on components, features in real time and an architecture based on at events.',
	'cardDevBoot': 'No more Bootstrap, just CSS',
	'cardDevBootText': 'Some time ago I did not miss anything other than Bootstrap or any another Frontend library to design my web pages, but fortunately, I trained in what has been the best tool in everything that CSS has been there; CSS Grids revolutionized completely the web design industry and I was not going to be left out of this. Now with this great tool I can design incredible, dynamic and complex grids that fit to any type of device, only with CSS!',
	'cardDevAni': 'Small details to fall in love',
	'cardDevAniText': 'Humans are incredible lovers of small details in any what we see and web design was not going to be the exception. The animations allow me to implement pleasant experiences that strengthen the bond that users have with the product, regardless the level, from the simplest to the most complex, an animation always will be a great ally to transmit emotions with your product',
	'cardDevAniPhra': 'The emotion remains in the memory. Be easy to remember.',
	'cardDesBran': 'The usefulness of branding',
	'cardDesBranTextF': 'Your brand is what your customers first perceive and our goal It is always be well presented. Well, my job is make your mark impeccable giving you the tools to convey a clean and coherent message that can be remembered easily.',
	'cardDesBranTextS': 'Do not forget that an efficient brand identity integrates all the elements of the brand within a coherent message that differentiates and highlights between the rest. Never discard the most discreet but visible part of your brand because The first impression is the one that sells.',
	'cardDesBranPhra': 'The design is the silent ambassador of your brand. - Paul Rand',
	'cardDesUI': 'Something called UI/UX',
	'cardDesUITextF': 'UX (User Experience), in this case, what is intended is to focus the efforts of designing a digital product towards the understanding of the different user types. Create an application based on the user and their needs.',
	'cardDesUITextS': 'UX allows me to create comforting, coherent and decisive experiences against a specific need, resulting in an increase in connections that exist between your product or service and your users.',
	'cardDesUITextT': 'Moving on to the other topic. UI (User Interface) is the interface of a product that in practice is intimately related to the UX, this is part of that experience of use and this is where the user-centered needs research skills they give us the path to follow in the graphic construction of the interface.',
	'cardDesUIPhra': "An interface is like a joke: if you have to explain it, it's because it's bad. - Juani Ruiz Echazú"
}
