'use strict'

export default {
	'titleDesign': 'Diseño Gráfico',
	'titleDevelop': 'Desarrollo Web',
	'titleGaming': 'Video Juegos',
	'homeMenu': 'Home',
	'designMenu': 'Diseño Gráfico',
	'developMenu': 'Desarrollo Web',
	'gamingMenu': 'Video Juegos',
	'adviceText': 'Toca para aprender un poquito más de mí.',
	'designCardTitle': 'Diseño Gráfico',
	'developCardTitle': 'Desarrollo Web',
	'gamingCardTitle': 'Video Juegos',
	'abilities': 'Habilidades',
	'genre': 'Géneros',
	'cardHabIllustration': 'Ilustración Web',
	'cardHabUX': 'Diseño de UI/UX',
	'cardHabJS': 'Aplicaciones JavaScript',
	'cardHabNode': 'Servidores NodeJS',
	'cardHabWebDes': 'Diseño Web',
	'cardHabAni': 'Animaciones Web',
	'cardHabResp': 'Diseño Responsive',
	'cardHabApi': 'Creación de APIs',
	'cardCreative': 'Creativo',
	'cardEffective': 'Efectivo',
	'cardAgil': 'Ágil',
	'cardExpressive': 'Expresivo',
	'cardClean': 'Limpio',
	'cardReadable': 'Legible',
	'cardQuick': 'Rápido',
	'cardFunctional': 'Funcional',
	'cardAmazing': 'Asombroso',
	'cardMagic': 'Mágico',
	'cardFunny': 'Divertido',
	'cardGenreAct': 'Acción',
	'cardGenreAdv': 'Aventura',
	'cardGenreSpo': 'Deportes',
	'cardGenreHor': 'Horror de supervivencia',
	'cardPrinciples': 'Valores',
	'cardLeader': 'Liderazgo',
	'cardRespect': 'Respeto',
	'cardRespon': 'Responsabilidad',
	'cardPerse': 'Perseverancia',
	'cardSelf': 'Autodidacta',
	'cardSelfC': 'Autocrítico',
	'cardReal': 'Realista',
	'cardAbout': 'Un poco sobre mí',
	'cardAboutTextF': "Mi nombre es Steven Anaya, tengo 21 años y estudié Ingeniería de Software 6 semestres pero por decisiones propias me retiré para empezar un proceso de aprendizaje constante y evolutivo. Hasta el día de hoy mi carrera como autodidacta ha	dado resultados increíbles que difícilmente hubiese alcanzado antes.",
	'cardAboutTextS': 'Sin duda, el abandonar mis estudios universitarios fue la decisión más dificil de tomar hasta el día de hoy, pero tengo el orgullo y más que nada la capacidad de decir que me he convertido en un diseñador y desarrollador web gracias a la constancia que he puesto en mi proceso de aprendizaje.',
	'cardTools': 'Mis herramientas de aprendizaje',
	'cardToolsText': 'Sería soberbio al decir con certeza que todo mi conocimiento es estructurado totalmente por mi. Debo un gran agradecimiento a todas aquellas plataformas virtuales y a aquellos medios tradicionales que brindan conocimiento claro e útil. Platzi.co es una plataforma en la que he puesto mis cartas para formarme como un profesional en temas digitales y hasta la fecha, después de 4 años, me siguen sorprendiendo con contenido académico de una calidad increíble que me permiten estar al tanto de las demandas en la industria.',
	'cardGamingInt': "Más que solo 'Muñequitos'",
	'cardGamingIntTextF': 'Los videojuegos forman parte de la vida de algunas personas como una necesidad de poder imaginar, sentir, vivir y recordar experiencias que dificilmente se dan en la vida diaria. Yo crecí envuelto de grandes experiencias que fueron mejorando al pasar los años y sería ingrato no devolverle un poco de lo mucho que me han aportado, aunque sea por este medio.',
	'cardGamingIntTextS': "Una parte significativa de mis recuerdos se los debo a los videojuegos porque evocaron en mi una cantidad inimaginable de sentimientos, que como se espera, la mayoría son gratos y positivos. Además, para no dejar nada atrás, me siento en deber de darle mención a grandes titulos como Super Mario World, Donkey Kong, Twisted Metal, Battlefield, Call Of Duty , Crash Saga, Halo, Dante's Inferno, Grand Theft Auto, Mortal Kombat, Resident Evil, Tomb Raider y algunos que por cuestión de memoria, más que otra cosa, no aparecen aquí.",
	'cardGamingLast': 'Un propósito deseado',
	'cardGamingLastText': 'En un principio supe que los videojuegos requerían un montón de habilidades no solo técnicas, sino también artisticas, que avivaron un profundo interés por la creación de videojuegos. Hoy tengo puesto en mi lista de "Cosas increíbles por hacer", convertirme en un desarrollador de videojuegos en donde siento que puedo explotar todo lo que me ha traído mi proceso de aprendizaje autodidacta.',
	'cardDevClean': 'Código limpio y legible por delante',
	'cardDevCleanText': 'Las buenas prácticas y el código sostenible son dos principios fundamentales en mi diario vivir de desarrollador. Cuando trabajamos bajo estas premisas nuestro entorno de trabajo se ve beneficiado potenciando nuestro talento humano y técnico.',
	'cardDevConc': 'Alta concurrencia y otras cositas',
	'cardDevConcText': 'Hoy en día es fundamental crear aplicaciones altamente escalables debido a que los productos tecnológicos tienden cada vez a crecer abismalmente con el paso del tiempo. NodeJS y un stack JavaScript me permiten crear aplicaciones con un gran soporte a grandes cantidades de peticiones, con una estructura basada en componentes, características totalmente en tiempo real y una arquitectura basada en eventos.',
	'cardDevBoot': 'No más Bootstrap, solo CSS',
	'cardDevBootText': 'Hace tiempo atrás no me se me pasaba nada más que Bootstrap o cualquier otra libreria Frontend para diseñar mis paginas web, pero afortunadamente, me capacité en lo que ha sido la mejor herramienta en todo lo que lleva CSS existiendo; CSS Grids revolucionó completamente la industria del diseño web y yo no iba a quedar fuera de esto. Ahora con esta gran herramienta puedo diseñar increíbles, dinámicas y complejas grillas que se adaptan a cualquier tipo de dispositivo, ¡Solo con CSS!.',
	'cardDevAni': 'Pequeños detalles que enamoran',
	'cardDevAniText': 'Los seres humanos somos increbles amantes de los pequeños detalles en cualquier cosa que vemos y claro el diseño web no iba a ser la excepción. Las animaciones me permiten implementar experiencias agradables que fortifican el lazo que tienen los usuarios con el producto, sin importar el grado, desde lo más simple hasta lo más complejo, una animación siempre será un gran aliado para transmitir emociones con tu producto.',
	'cardDevAniPhra': 'La emoción queda en la memoria. Sé fácil de recordar.',
	'cardDesBran': 'La utilidad del Branding',
	'cardDesBranTextF': 'Tu marca es lo que primero perciben tus clientes y nuestro objetivo es siempre estar bien presentados. Pues bien, mi trabajo es dejar tu marca impecable dandole las herramientas para transmitir un mensaje limpio y coherente que pueda ser recordado fácilmente.',
	'cardDesBranTextS': 'No olvides que una identidad de marca eficiente integra todos los elementos de la marca dentro de un mensaje coherente que diferencia y destaca entre el resto. Nunca descartes la parte más discreta pero visible de tu marca porque la primera impresión es la que vende.',
	'cardDesBranPhra': 'El diseño es el embajador silencioso de tu marca. - Paul Rand',
	'cardDesUI': 'Algo llamado UX y UI',
	'cardDesUITextF': 'UX (Experiencia de Usuario), en este caso, lo que pretende es enfocar los esfuerzos del diseño de un producto digital hacia el entendimiento de los diferentes tipos de usuario. Crear una aplicación basada en el usuario y sus necesidades.',
	'cardDesUITextS': 'UX me permite crear experiencias confortantes, coherentes y resolutivas frente a una necesidad especifica dejando como resultado un incremento en las conexiones que existen entre tu producto o servicio y tus usuarios.',
	'cardDesUITextT': 'Pasando al otro tema. UI (Interfaz de Usuario) es la interfaz de un producto que en la práctica esta intimamente relacionado con la UX, esta forma parte de esa experiencia de uso y es aquí donde las habilidades en investigación de necesidades centradas en el usuario nos dan el camino a seguir en la construcción gráfica de la interfaz.',
	'cardDesUIPhra': 'Una interfaz es como un chiste: si la tienes que explicar es porque es mala. - Juani Ruiz Echazú'
}
